version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
      MYSQL_ROOT_HOST: "%"

    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql

  springapp:
    image: neilmonastiri/neilmonastiri-5ds1-g3-kaddem
    container_name: springapp
    restart: always
    depends_on:
      - mysqldb
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/kaddem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect

volumes:
  mysqldb_data:
